package com.avancent.betterrtp2ezrtp;

import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.util.*;

/**
 * Reads BetterRTP config and produces EzRTP YAML strings.
 */
public class ConfigMapper {

    private final File serverRoot;
    private final MigrationReport report;

    public ConfigMapper(File serverRoot, MigrationReport report) {
        this.serverRoot = serverRoot;
        this.report = report;
    }

    // -------------------------------------------------------------------------
    // Entry point
    // -------------------------------------------------------------------------

    public Map<String, String> map() {
        File betterRtpConfig = new File(serverRoot, "plugins/BetterRTP/config.yml");
        if (!betterRtpConfig.exists()) {
            throw new IllegalStateException("plugins/BetterRTP/config.yml not found");
        }

        YamlConfiguration src = YamlConfiguration.loadConfiguration(betterRtpConfig);

        Map<String, String> outputs = new LinkedHashMap<>();
        outputs.put("rtp.yml",     buildRtpYml(src));
        outputs.put("limits.yml",  buildLimitsYml(src));
        outputs.put("storage.yml", buildStorageYml());
        outputs.put("config.yml",  buildConfigYml());
        return outputs;
    }

    // -------------------------------------------------------------------------
    // rtp.yml
    // -------------------------------------------------------------------------

    private String buildRtpYml(YamlConfiguration src) {
        StringBuilder sb = new StringBuilder();
        sb.append("# EzRTP rtp.yml — generated by BetterRTP2EzRTP\n");
        sb.append("# Review all values before going live.\n\n");

        // Default world block
        sb.append("worlds:\n");
        sb.append("  default:\n");
        appendWorldBlock(sb, src.getConfigurationSection("Default"), "    ", true);

        // CustomWorlds
        ConfigurationSection custom = src.getConfigurationSection("CustomWorlds");
        List<String> disabled = src.getStringList("DisabledWorlds");
        if (custom != null) {
            for (String world : custom.getKeys(false)) {
                if (disabled.contains(world)) {
                    report.addDropped("CustomWorlds." + world + " — listed in DisabledWorlds, skipped");
                    continue;
                }
                sb.append("  ").append(world).append(":\n");
                appendWorldBlock(sb, custom.getConfigurationSection(world), "    ", false);
                report.addMapped("CustomWorlds." + world + " → worlds." + world);
            }
        }

        if (!disabled.isEmpty()) {
            report.addDropped("DisabledWorlds " + disabled + " — simply omitted from worlds config");
        }

        return sb.toString();
    }

    private void appendWorldBlock(StringBuilder sb, ConfigurationSection sec, String indent, boolean isDefault) {
        int maxRadius = getInt(sec, "MaxRadius", 5000);
        int minRadius = getInt(sec, "MinRadius", 100);
        int centerX   = getInt(sec, "CenterX", 0);
        int centerZ   = getInt(sec, "CenterZ", 0);
        String shape  = getString(sec, "Shape", "square").toLowerCase(Locale.ROOT);

        sb.append(indent).append("max-radius: ").append(maxRadius).append("\n");
        sb.append(indent).append("min-radius: ").append(minRadius).append("\n");
        sb.append(indent).append("center-x: ").append(centerX).append("\n");
        sb.append(indent).append("center-z: ").append(centerZ).append("\n");

        // Shape → search-pattern
        String pattern = shape.equals("circle") ? "circle" : "square";
        sb.append(indent).append("search-pattern: ").append(pattern).append("\n");

        if (isDefault) {
            report.addMapped("Default.MaxRadius → worlds.default.max-radius (" + maxRadius + ")");
            report.addMapped("Default.MinRadius → worlds.default.min-radius (" + minRadius + ")");
            report.addMapped("Default.CenterX/CenterZ → worlds.default.center-x/z (" + centerX + ", " + centerZ + ")");
            report.addMapped("Default.Shape (" + shape + ") → worlds.default.search-pattern (" + pattern + ")");
        }

        // Countdown (Delay.Time lives at top-level in BetterRTP, pulled from root in default only)
        if (isDefault && sec != null) {
            // Delay is a top-level key in BetterRTP, not nested under Default
        }

        // Biomes
        List<String> biomes = sec != null ? sec.getStringList("Biomes") : Collections.emptyList();
        if (!biomes.isEmpty()) {
            sb.append(indent).append("biomes:\n");
            sb.append(indent).append("  include:\n");
            for (String b : biomes) sb.append(indent).append("    - ").append(b).append("\n");
            if (isDefault) report.addMapped("Default.Biomes → worlds.default.biomes.include");
        }

        // BlacklistedBlocks
        List<String> blocks = sec != null ? sec.getStringList("BlacklistedBlocks") : Collections.emptyList();
        if (!blocks.isEmpty()) {
            sb.append(indent).append("unsafe-blocks:\n");
            for (String b : blocks) sb.append(indent).append("  - ").append(b).append("\n");
            if (isDefault) report.addMapped("Default.BlacklistedBlocks → worlds.default.unsafe-blocks");
        }
    }

    // -------------------------------------------------------------------------
    // limits.yml
    // -------------------------------------------------------------------------

    private String buildLimitsYml(YamlConfiguration src) {
        StringBuilder sb = new StringBuilder();
        sb.append("# EzRTP limits.yml — generated by BetterRTP2EzRTP\n\n");

        // Cooldown
        int cooldown = 0;
        ConfigurationSection cooldownSec = src.getConfigurationSection("Cooldown");
        if (cooldownSec != null) {
            cooldown = cooldownSec.getInt("Time", 0);
            report.addMapped("Cooldown.Time → cooldown-seconds (" + cooldown + ")");
        }
        sb.append("cooldown-seconds: ").append(cooldown).append("\n");

        // Bypass permission
        sb.append("\n");
        sb.append("bypass-permissions:\n");
        sb.append("  cooldown: ezrtp.bypass.cooldown\n");
        report.addMapped("betterrtp.bypass.cooldown → ezrtp.bypass.cooldown");

        // LockAfter — no equivalent
        if (src.contains("LockAfter") && src.getInt("LockAfter", 0) > 0) {
            report.addManual("LockAfter: " + src.getInt("LockAfter")
                    + " — EzRTP has no equivalent for infinite cooldown after N uses. "
                    + "Consider a custom permission or economy hook.");
        }

        // PermissionGroups — no equivalent
        if (src.contains("PermissionGroups")) {
            report.addManual("PermissionGroups — EzRTP does not support per-group cooldowns natively. "
                    + "Replicate via LuckPerms contexts or a permissions-based cooldown plugin.");
        }

        // Delay.Time → countdown-seconds goes in rtp.yml per-world; note it here too
        ConfigurationSection delaySec = src.getConfigurationSection("Delay");
        if (delaySec != null) {
            int delay = delaySec.getInt("Time", 0);
            sb.append("\n# countdown-seconds is set per-world in rtp.yml\n");
            sb.append("# Delay.Time was: ").append(delay).append(" second(s)\n");
            report.addMapped("Delay.Time (" + delay + "s) noted — set countdown-seconds in rtp.yml per world");
        }

        // RTPOnDeath — no equivalent
        if (src.contains("RTPOnDeath") && src.getBoolean("RTPOnDeath", false)) {
            report.addManual("RTPOnDeath: true — EzRTP does not support automatic RTP on death. "
                    + "Use a compatible death-RTP plugin (e.g. DeathTP) alongside EzRTP.");
        }

        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // storage.yml  (no BetterRTP equivalent — sensible defaults)
    // -------------------------------------------------------------------------

    private String buildStorageYml() {
        report.addMapped("storage.yml — generated with default YAML flat-file storage");
        return "# EzRTP storage.yml — generated by BetterRTP2EzRTP\n\n"
                + "storage-type: yaml\n"
                + "# Change to 'mysql' and fill in credentials if you need database storage.\n"
                + "mysql:\n"
                + "  host: localhost\n"
                + "  port: 3306\n"
                + "  database: ezrtp\n"
                + "  username: root\n"
                + "  password: ''\n";
    }

    // -------------------------------------------------------------------------
    // config.yml  (EzRTP general settings — safe defaults)
    // -------------------------------------------------------------------------

    private String buildConfigYml() {
        report.addMapped("config.yml — generated with safe defaults");
        return "# EzRTP config.yml — generated by BetterRTP2EzRTP\n\n"
                + "# Set to false once you have confirmed migration is working.\n"
                + "debug: false\n\n"
                + "messages:\n"
                + "  prefix: '&6[EzRTP]&r '\n"
                + "  teleporting: '&aTeleporting you to a random location...'\n"
                + "  cooldown: '&cYou must wait &e{time}&c before using RTP again.'\n"
                + "  success: '&aTeleported to &e{x}&a, &e{y}&a, &e{z}&a in &e{world}&a.'\n";
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private int getInt(ConfigurationSection sec, String key, int def) {
        if (sec == null) return def;
        return sec.getInt(key, def);
    }

    private String getString(ConfigurationSection sec, String key, String def) {
        if (sec == null) return def;
        return sec.getString(key, def);
    }
}
